---
- name: <r_sys_banner_t_common> install the figlet package
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
    disable_gpg_check: yes
    #allow_downgrade: yes
  loop:
    - figlet

- name: <r_sys_banner_t_common> generate ascii art banner
  command:
  #become: yes
  #become_method: su
  #become_user:
  #become_flags: "-s /bin/sh"
  args:
    cmd: "figlet {{ sys_banner_content }}"
    #chdir:
    # A filename or (since 2.0) glob pattern.
    # If it already exists, this step *won't* be run.
    #creates:

    # A filename or (since 2.0) glob pattern.
    # If it already exists, this step *will* be run.
    #remove:
  register: figlet_result

- name: <r_sys_banner_t_common> template a file to /etc/motd
  template:
    src: motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: "0644"
    #validate:
    #backup: yes
